import {Component} from '@angular/core';

@Component({
  selector: 'my-app',
  templateUrl: 'app/components/welcome/welcome.html'
})

export class WelcomeComponent {
  title = 'Yay!'
  subtitle = 'You\'re all setup. Everything is awesome!'
  info = 'This welcome message is generated by Angular, and can be found in app/components/welcome/welcome.jade'
}
